### ISSUE TITLE
address variable in bhindex.conf ignored

### ISSUE THREAD

**Issue by zidz** [rawler/bhindex#11]
The address variable under [BITHORDE] in bhindex.conf is ignored rendering bhindex unusable if the bithorde socket file in placed somewhere else than /var/run/bithorde/socket.

May be line 100-102 in bhindex/config.py:
`
config = VersioningConfigParser(deprecations={
        ('BITHORDE', 'address'): ('BITHORDE', 'unixsocket')
    })
`

Million dollar question, how could we set custom path to Bithorde unix socket is both is depricated?

**Comment by rawler** [comment]
Not sure why you believe it to be ignored in config? I use that option every day for cross-testing.

The line you are referring to is a deprecation of the unixsocket-option, that was renamed to address. It's a back-mapping, meaning if someone is still setting unixsocket, it will be used, but with a deprecation-warning.

Please double-check your config. I.E, are you sure you've actually pointed bithorde to the config you're editing?

**Comment by zidz** [comment]
I've had a old bhindex config with old path but still it tried to reach the socket through the new standard path. That's why this happened, probably a glitch then.
